version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    image: '${COMPOSE_PROJECT_NAME}_app'
    container_name: '${COMPOSE_PROJECT_NAME}_app'
    restart: unless-stopped
    environment:
      CONTAINER_ROLE: app
    volumes:
      - .:/app

  front:
    build: ./.docker/nginx
    image: '${COMPOSE_PROJECT_NAME}_nginx:alpine'
    container_name: '${COMPOSE_PROJECT_NAME}_front'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - .:/app
    depends_on:
      - app
    links:
      - app
